"""Jinja2 environments and the two render functions. All markup comes from the templates."""

from __future__ import annotations

from datetime import UTC, date, datetime
from functools import lru_cache
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from bugflow.enums import label_of
from bugflow.reports.data import ReportData
from bugflow.reports.diagram import build_flow_diagram
from bugflow.reports.escape import md, md_block

# The HTML template names the same exact version in its CDN URL (a unit test keeps them equal).
MERMAID_VERSION = "11.4.1"
TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"


def _mermaid_block(diagram: str) -> str:
    # The diagram is generated by code and every label is encoded, so it holds no backtick.
    return f"```mermaid\n{diagram}\n```"


def _iso(value: date) -> str:
    return value.isoformat()


def _opened(value: datetime) -> str:
    return value.astimezone(UTC).strftime("%Y-%m-%d %H:%M UTC")


def _days(value: int) -> str:
    return f"{value} day" if value == 1 else f"{value} days"


def _environment(autoescape: bool) -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATE_DIR)),
        autoescape=autoescape,
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    env.filters.update(
        {
            "label": label_of,
            "md": md,
            "md_block": md_block,
            "mermaid_block": _mermaid_block,
            "iso": _iso,
            "opened": _opened,
            "days": _days,
        }
    )
    return env


@lru_cache(maxsize=1)
def markdown_environment() -> Environment:
    return _environment(autoescape=False)


@lru_cache(maxsize=1)
def html_environment() -> Environment:
    return _environment(autoescape=True)


def render_markdown(data: ReportData) -> str:
    """The Markdown report: starts with the title heading and ends with one newline."""
    template = markdown_environment().get_template("report.md.j2")
    text = template.render(data=data, diagram=build_flow_diagram(data))
    return text.rstrip("\n") + "\n"


def render_html(data: ReportData) -> str:
    """The standalone HTML report with auto-escaped values."""
    template = html_environment().get_template("report.html.j2")
    text = template.render(data=data, diagram=build_flow_diagram(data))
    return text.rstrip("\n") + "\n"
